#!/bin/bash

backup_folder="${HOME}/Desktop/dotfiles_backups_$(date +'%S%M%H%d%m%Y')"

mkdir $backup_folder

echo "Setting up homebrew..."
source ./brew/setup_brew
echo "Setting up zsh..."
source ./zsh/setup_zsh
echo "Setting up vim..."
source ./vim/setup_vim
echo "Setting up sublime..."
source ./sublime/setup_sublime

# Git
echo "Configuring Git..."
ln -svi ~/dotfiles/git/.gitconfig ~
ln -svi ~/dotfiles/git/.gitignore_global ~

# Ruby/Gems
ln -svi ~/dotfiles/ruby/gems/.gemrc ~

echo "*******************************"
echo "*******************************"
echo "***-------------------------***"
echo "*** Dotfiles setup complete ***"
echo "***-------------------------***"
echo "*******************************"
echo "*******************************"


